tap "go-task/tap"
tap "homebrew/bundle"
brew "docker-compose"
brew "git"
brew "git-secrets"
brew "mas"
brew "tree"
brew "zsh"
brew "zsh-autosuggestions"
brew "go-task/tap/go-task"
cask "bluesnooze"
cask "clipy"
cask "displaylink"
cask "docker"
cask "figma"
cask "obs"
cask "obsidian"
cask "postman"
cask "raycast"
cask "scroll-reverser"
cask "sequel-ace"
cask "visual-studio-code"
cask "vivaldi"
cask "zed"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bmewburn.vscode-intelephense-client"
vscode "chakrounanas.turbo-console-log"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "gruntfuggly.todo-tree"
vscode "ionutvmi.path-autocomplete"
vscode "mehedidracula.php-namespace-resolver"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-vscode-remote.remote-containers"
vscode "mylesmurphy.prettify-ts"
vscode "onecentlin.laravel-blade"
vscode "onecentlin.laravel5-snippets"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "streetsidesoftware.code-spell-checker"
vscode "tonybaloney.vscode-pets"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
