# Aliases
# ls系のエイリアス
alias ls='ls -GF'
alias la='ls -aGF'
alias ll='ls -lGF'

# Git関連のエイリアス
alias g='git'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gps='git push'
alias gpl='git pull'
alias gplm='git pull origin main'
alias gs='git status'
alias gd='git diff'
alias gb='git branch'
alias gsw='git switch'
alias gswc='git switch -c'
alias gswm='git switch main'
alias gl='git log --oneline --graph --decorate'
alias grs='git reset'
alias grh='git reset --hard'
alias gst='git stash'
alias gstp='git stash pop'

# Docker関連のエイリアス
alias d='docker'
alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcd='docker-compose down'
alias dcr='docker-compose restart'
alias dcl='docker-compose logs'
alias dclf='docker-compose logs -f'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias drm='docker rm'
alias drmi='docker rmi'
alias dexec='docker exec -it'
alias drun='docker run --rm -it'
alias dstop='docker stop'
alias dstart='docker start'
alias drestart='docker restart'
alias dprune='docker system prune -f'

# よく使うコマンドの短縮形
# alias v='vim'
# alias c='cd' 
